name: ML CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ” Checkout repository
        uses: actions/checkout@v3

      - name: ğŸ§ª Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: mlflow-env
          environment-file: MLProject/conda.yaml
          auto-activate-base: false

      - name: ğŸ§° Install Python dependencies
        run: |
          pip install mlflow docker

      - name: ğŸ“¦ Run MLflow Project (retrain model)
        working-directory: ./MLProject
        run: |
          export MLFLOW_TRACKING_URI=./mlruns
          mlflow run . --env-manager=local

      - name: ğŸ” Build Docker image from MLflow model
        working-directory: ./MLProject
        run: |
          # Ambil RUN ID terakhir dari mlruns
          RUN_ID=$(ls -td mlruns/0/* | head -1 | xargs -n1 basename)

          echo "RUN_ID=$RUN_ID"
          
          # Build Docker image dari model
          mlflow models build-docker -m mlruns/0/$RUN_ID/artifacts/model -n mlflow_rf_image

      - name: ğŸš€ Push Docker image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag mlflow_rf_image baiqega/mlflow-rf:latest
          docker push baiqega/mlflow-rf:latest
